"use server";

import { z } from "zod";
import { updateTag } from "next/cache";
import { after } from "next/server";
import { createClient } from "../server";
import { getUser } from "../auth";
import { checkoutSchema } from "@/lib/validation";
import { guardPublicAction, consumeDurableLimit } from "@/lib/rate-limit";
import { normalizeBdPhone } from "@/lib/phone";
import { normaliseSizeValue } from "@/lib/product-size";
import { logger, logFailure } from "@/lib/logger";
import { dispatchOrderNotifications } from "@/lib/email/dispatch";
import type { CartItem } from "@/types";
import type { ActionResult } from "./auth";
import { isSupabaseConfigured } from "../env";

/**
 * Checkout.
 *
 * Nothing about the money is trusted from the browser. The action resolves the
 * cart lines to variant ids and then hands off to `place_order()`, which
 * re-reads every price, recalculates the delivery fee from store settings,
 * re-validates the coupon, locks each variant row and deducts stock — all
 * inside one transaction. The totals the customer saw are never sent.
 */

const checkoutInput = checkoutSchema.omit({ items: true }).extend({
  items: z
    .array(
      z.object({
        productId: z.string().uuid(),
        size: z.string().min(1).max(60),
        colour: z.string().min(1).max(60),
        quantity: z.number().int().min(1).max(20),
      }),
    )
    .min(1)
    .max(50),
  // Generated by the browser once per checkout attempt. Replaying it returns
  // the original order instead of creating a second one, which is what stops a
  // double-tap or a retry after a flaky connection from charging twice.
  idempotencyKey: z.string().uuid().optional(),
});

type OrderResult = {
  orderNumber: string;
  trackingToken: string;
  total: number;
  replayed: boolean;
};

/** Maps a database error onto a message a customer can act on. */
function checkoutError(message: string): ActionResult {
  if (message.includes("out_of_stock")) {
    return { ok: false, message: "One or more items are out of stock." };
  }
  if (message.includes("invalid_coupon")) {
    return { ok: false, message: "This coupon is invalid or no longer available." };
  }
  if (message.includes("rate_limited")) {
    return { ok: false, message: "You have placed several orders very recently. Please wait a few minutes before trying again." };
  }
  if (message.includes("duplicate_order")) {
    return { ok: false, message: "An order with these details was just placed. Check your order history before trying again." };
  }
  if (message.includes("cod_disabled") || message.includes("online_payment_unavailable")) {
    return { ok: false, message: "The store is not accepting new orders at the moment. Please try again later." };
  }
  if (message.includes("invalid_customer_or_address")) {
    return { ok: false, message: "Check your checkout details and try again." };
  }
  if (message.includes("invalid_variant")) {
    return { ok: false, message: "A selected product option is no longer available." };
  }
  if (message.includes("invalid_shipping_location") || message.includes("invalid_delivery_zone")) {
    return {
      ok: false,
      message: "Check your delivery address and area, then try again.",
    };
  }
  return { ok: false, message: "Your order could not be placed. Nothing has been ordered — please try again." };
}

async function placeOrderAction(input: unknown): Promise<ActionResult<OrderResult>> {
  const parsed = checkoutInput.safeParse(input);
  if (!parsed.success) {
    return {
      ok: false,
      message: "Check your checkout details and try again.",
      fieldErrors: parsed.error.flatten().fieldErrors as Record<string, string[]>,
    };
  }
  if (!isSupabaseConfigured()) {
    return { ok: false, message: "Supabase has not been configured yet." };
  }

  // First line of defence, before any database work. The durable limits live
  // in Postgres and are keyed on the phone number as well.
  const { fingerprint, result: throttle } = await guardPublicAction("checkout", 8, 600);
  if (!throttle.allowed) {
    return {
      ok: false,
      message:
        "You have placed several orders very recently. Please wait a few minutes before trying again.",
    };
  }

  const supabase = await createClient();
  const user = await getUser();

  // Resolve every requested line to a real, active variant in one query rather
  // than one round trip per line.
  const productIds = [...new Set(parsed.data.items.map((item) => item.productId))];
  const { data: variants, error: variantError } = await supabase
    .from("product_variants")
    .select("id,product_id,size,colour_en,is_active")
    .in("product_id", productIds)
    .eq("is_active", true);

  if (variantError) {
    logFailure("checkout.variant_lookup_failed", variantError, {
      lines: parsed.data.items.length,
    });
    return {
      ok: false,
      message: "Your order could not be placed. Nothing has been ordered — please try again.",
    };
  }

  const resolved: { variantId: string; quantity: number }[] = [];
  for (const item of parsed.data.items) {
    // A cart saved before either rename still has to match a live variant.
    // "Undready" and "Unstitched" both resolve to "Unready"; the database does
    // the same inside resolve_cart_lines(), because the browser is not the
    // authority on which variant is being bought.
    const size = normaliseSizeValue(item.size);
    const match = variants?.find(
      (variant) =>
        variant.product_id === item.productId &&
        variant.size === size &&
        variant.colour_en === item.colour,
    );
    if (!match) return { ok: false, message: "A selected product option is no longer available." };
    resolved.push({ variantId: match.id, quantity: item.quantity });
  }

  const { data, error } = await supabase.rpc("place_order", {
    p_customer: {
      name: parsed.data.customerName,
      email: parsed.data.customerEmail ?? "",
      phone: normalizeBdPhone(parsed.data.customerPhone) ?? parsed.data.customerPhone,
    },
    // The country is recorded, not asked: the store ships within Bangladesh
    // only, so a selector would be a required field with one option.
    p_shipping_address: { ...parsed.data.shippingAddress, country: "Bangladesh" },
    p_items: resolved,
    // Fixed, not client-supplied: the store runs one delivery option and one
    // payment method, and place_order() rejects anything else outright.
    p_delivery_method: "standard",
    p_payment_method: "cash_on_delivery",
    p_coupon_code: parsed.data.couponCode || null,
    p_customer_note: parsed.data.customerNote || null,
    p_idempotency_key: parsed.data.idempotencyKey ?? null,
    p_client_fingerprint: fingerprint,
  });

  if (error) {
    // The raw message can name SKUs and constraints, so it is logged rather
    // than returned.
    logFailure("checkout.place_order_failed", error, {
      hasUser: Boolean(user),
      lines: resolved.length,
    });
    return checkoutError(error.message);
  }

  const order = data as unknown as OrderResult;
  logger.info("checkout.order_placed", {
    orderNumber: order.orderNumber,
    replayed: order.replayed,
    hasUser: Boolean(user),
  });

  // place_order() deducts variant stock transactionally. Purge the shared
  // public catalogue cache before another shopper can see the old quantity.
  if (!order.replayed) updateTag("catalogue");

  // The order is committed. Everything from here is best-effort: an email that
  // does not go out must never turn a successful order into a failed one, so
  // the response is returned immediately while Next keeps the best-effort
  // dispatch alive after the response. A replayed order does not re-notify --
  // the outbox rows for it are already sent.
  if (!order.replayed) {
    after(async () => {
      await dispatchOrderNotifications(order.orderNumber, order.trackingToken);
    });
  }

  return { ok: true, data: order };
}

/**
 * What the checkout form sends.
 *
 * Written out rather than derived from the schema with `z.infer`, because the
 * schema's *output* type is the validated one — the delivery zone narrowed to
 * the two real zones, phone normalised, postal code nulled when blank — and the
 * browser is by definition sending the unvalidated input. Typing the boundary as
 * the schema's output would be a claim the client cannot make.
 */
export interface CheckoutDetails {
  customerName: string;
  customerEmail?: string;
  customerPhone: string;
  paymentMethod?: "cash_on_delivery";
  customerNote?: string;
  shippingAddress: {
    address: string;
    apartment?: string;
    city: string;
    postalCode?: string;
    deliveryZone: string;
  };
  couponCode?: string;
  idempotencyKey?: string;
}

export async function placeCartOrderAction(details: CheckoutDetails, items: CartItem[]) {
  return placeOrderAction({ ...details, items });
}

type CouponPreview = { discount: number; code?: string };

export async function previewCouponAction(
  code: string,
  subtotal: number,
  phone?: string,
): Promise<ActionResult<CouponPreview>> {
  const trimmed = code.trim().slice(0, 30);
  if (!trimmed) return { ok: false, message: "Enter a coupon code first." };
  if (!isSupabaseConfigured()) return { ok: false, message: "Supabase has not been configured yet." };
  if (!Number.isFinite(subtotal) || subtotal < 0) {
    return { ok: false, message: "This coupon code isn't valid or has expired." };
  }

  // Coupon codes are guessable, so trying them is throttled to stop the form
  // being used as an oracle to enumerate live promotions. The in-process check
  // is cheap; the durable one in Postgres is the authority, because a
  // serverless deployment has many processes and each starts with an empty
  // counter.
  const { fingerprint, result } = await guardPublicAction("coupon", 15, 600);
  if (!result.allowed || !(await consumeDurableLimit("coupon", fingerprint))) {
    return { ok: false, message: "Too many coupon attempts. Please wait a few minutes." };
  }

  const supabase = await createClient();
  const user = await getUser();

  const { data, error } = await supabase.rpc("validate_coupon", {
    p_code: trimmed,
    p_subtotal: subtotal,
    p_user_id: user?.id ?? null,
    p_phone: normalizeBdPhone(phone) ?? null,
  });

  if (error) {
    logFailure("checkout.coupon_preview_failed", error);
    return { ok: false, message: "Could not check that coupon right now. Please try again." };
  }

  const preview = data as unknown as {
    valid: boolean;
    discount?: number;
    reason?: string;
    minimum?: number;
    code?: string;
  };

  if (!preview.valid) {
    if (preview.reason === "minimum_not_met") return { ok: false, message: "Your order doesn't meet this coupon's minimum amount yet." };
    if (preview.reason === "per_customer_limit") {
      return { ok: false, message: "You have already used this coupon." };
    }
    return { ok: false, message: "This coupon code isn't valid or has expired." };
  }

  // Only the discount is returned. The authoritative amount is recalculated by
  // place_order() at submit time, so a stale preview can never become the
  // amount actually charged.
  return { ok: true, data: { discount: preview.discount ?? 0, code: preview.code } };
}

export async function trackGuestOrderAction(orderNumber: string, trackingToken: string) {
  if (!isSupabaseConfigured()) {
    return { ok: false as const, message: "Supabase has not been configured yet." };
  }

  // Tracking tokens are 48 hex characters, so brute force is impractical — but
  // the attempt rate is capped anyway, durably as well as in process.
  const { fingerprint, result } = await guardPublicAction("tracking", 20, 600);
  if (!result.allowed || !(await consumeDurableLimit("tracking", fingerprint))) {
    return {
      ok: false as const,
      message: "Too many tracking attempts. Please wait a few minutes.",
    };
  }

  const trimmedNumber = orderNumber.trim().slice(0, 40);
  const trimmedToken = trackingToken.trim().slice(0, 100);
  if (!trimmedNumber || trimmedToken.length < 32) {
    return { ok: false as const, message: "No order matched those tracking details." };
  }

  const supabase = await createClient();
  const { data, error } = await supabase.rpc("get_guest_order_tracking", {
    p_order_number: trimmedNumber,
    p_tracking_token: trimmedToken,
  });

  if (error || !data) return { ok: false as const, message: "No order matched those tracking details." };
  return { ok: true as const, data };
}
