/*
TARA -- DEVELOPMENT SEED CATALOGUE

  DO NOT RUN THIS AGAINST PRODUCTION.

Fourteen invented products with Unsplash photography, fabricated ratings and
made-up customer reviews. They exist so that a developer working against a fresh
local database has something to lay out, filter, sort, page through and check
out with.

This used to be the last 140 lines of TARA_COMPLETE_SETUP.sql, which meant that
installing the production schema also installed the fake catalogue. It is now a
separate file that no migration references, and it is deliberately NOT named
`seed.sql` -- the Supabase CLI runs a file of that name automatically as part of
`supabase db reset`, and nothing should install demonstration products without
being asked to.

Run it on purpose, against a local or staging database only:

  psql "$LOCAL_DATABASE_URL" -f supabase/seed/development_seed.sql

To take the seed products back out again:

  delete from public.products where product_code like 'TR-%';

The delete cascades to their images, variants and reviews.
*/

begin;

-- Size values here are 'Unready', the current spelling of the placeholder for a
-- product sold as fabric. The SKUs still contain "UNDREADY" from an older
-- naming pass -- deliberately left alone, because a SKU is an opaque identifier
-- staff use to find stock, not a word anyone reads.

insert into public.products(slug,name_en,description_en,category_id,collection_id,base_price,compare_at_price,fabric_en,product_code,status,is_new,is_featured,is_best_seller,care_instructions_en,tags,unstitched_details,ready_made_details,average_rating,review_count) select 'embroidered-lawn-unstitched-set', 'Embroidered Lawn Unstitched Set', 'A refined ivory lawn three piece with hand-finished floral embroidery along the neckline and sleeves, paired with a soft chiffon dupatta.', c.id, col.id, 2850, 3400, 'Pure Lawn Cotton', 'TR-UN-101', 'active', true, true, true, 'Dry clean recommended. If hand washing, use cold water and mild detergent. Do not wring embroidered panels.', array['embroidered','lawn','festive'], '{"kameezFabric":{"en":"Pure Lawn Cotton, 3.15 metres","bn":"খাঁটি লন কটন, ৩.১৫ মিটার"},"salwarFabric":{"en":"Cambric Cotton, 2.5 metres","bn":"ক্যামব্রিক কটন, ২.৫ মিটার"},"dupattaFabric":{"en":"Soft Chiffon, 2.5 metres","bn":"নরম শিফন, ২.৫ মিটার"},"workDetails":{"en":"Hand-finished thread embroidery on neckline and sleeves","bn":"গলা ও হাতায় হাতে করা সুতার এমব্রয়ডারি"},"fabricLength":{"en":"Total 8.15 metres (undready)","bn":"মোট ৮.১৫ মিটার (আনস্টিচড)"},"colourInfo":{"en":"Ivory base with wine embroidery thread","bn":"আইভরি বেসের উপর ওয়াইন রঙের সুতার কাজ"}}'::jsonb, 'null'::jsonb, 4.7, 32
from public.categories c left join public.collections col on col.slug='festive' where c.slug='unstitched-three-piece'
on conflict (slug) do update set name_en=excluded.name_en,description_en=excluded.description_en,category_id=excluded.category_id,collection_id=excluded.collection_id,base_price=excluded.base_price,compare_at_price=excluded.compare_at_price,fabric_en=excluded.fabric_en,product_code=excluded.product_code,status=excluded.status,is_new=excluded.is_new,is_featured=excluded.is_featured,is_best_seller=excluded.is_best_seller,care_instructions_en=excluded.care_instructions_en,tags=excluded.tags,unstitched_details=excluded.unstitched_details,ready_made_details=excluded.ready_made_details;

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=900&h=1125&fit=crop&q=80&auto=format', 'Embroidered Lawn Unstitched Set', 0, true from public.products p where p.slug='embroidered-lawn-unstitched-set' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1483985988355-763728e1935b?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=900&h=1125&fit=crop&q=80&auto=format', 'Embroidered Lawn Unstitched Set', 1, false from public.products p where p.slug='embroidered-lawn-unstitched-set' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1445205170230-053b83016050?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-UN-101-UNDREADY-IVORY', 'Unready', 'Ivory', '#EDE6D9', 7, true from public.products where slug='embroidered-lawn-unstitched-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-UN-101-UNDREADY-WINE', 'Unready', 'Wine', '#6F263D', 7, true from public.products where slug='embroidered-lawn-unstitched-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.reviews(product_id,author_name,rating,comment_en,status,created_at) select p.id, 'Nusrat J.', 5, 'The fabric quality is beautiful and the embroidery is so delicate.', 'approved', '2026-06-02T00:00:00Z'::timestamptz from public.products p where p.slug='embroidered-lawn-unstitched-set' and not exists (select 1 from public.reviews existing where existing.product_id=p.id and existing.author_name='Nusrat J.' and existing.created_at='2026-06-02T00:00:00Z'::timestamptz);

insert into public.reviews(product_id,author_name,rating,comment_en,status,created_at) select p.id, 'Farzana A.', 4, 'Loved the colour, stitching took it to another level.', 'approved', '2026-05-20T00:00:00Z'::timestamptz from public.products p where p.slug='embroidered-lawn-unstitched-set' and not exists (select 1 from public.reviews existing where existing.product_id=p.id and existing.author_name='Farzana A.' and existing.created_at='2026-05-20T00:00:00Z'::timestamptz);

insert into public.products(slug,name_en,description_en,category_id,collection_id,base_price,compare_at_price,fabric_en,product_code,status,is_new,is_featured,is_best_seller,care_instructions_en,tags,unstitched_details,ready_made_details,average_rating,review_count) select 'floral-cotton-unstitched-set', 'Floral Cotton Unstitched Set', 'A pastel pink cotton three piece with delicate floral print, designed for warm-weather comfort and everyday elegance.', c.id, col.id, 2450, null, 'Printed Cotton', 'TR-UN-102', 'active', true, true, false, 'Machine washable in cold water. Iron on medium heat. Wash dark colours separately.', array['printed','cotton','everyday'], '{"kameezFabric":{"en":"Printed Cotton, 3 metres","bn":"প্রিন্টেড কটন, ৩ মিটার"},"salwarFabric":{"en":"Plain Cotton, 2.5 metres","bn":"প্লেইন কটন, ২.৫ মিটার"},"dupattaFabric":{"en":"Cotton Voile, 2.5 metres","bn":"কটন ভয়েল, ২.৫ মিটার"},"workDetails":{"en":"Digital floral print, no embellishment","bn":"ডিজিটাল ফুলেল প্রিন্ট, কোনো বাড়তি কাজ নেই"},"fabricLength":{"en":"Total 8 metres (undready)","bn":"মোট ৮ মিটার (আনস্টিচড)"},"colourInfo":{"en":"Pastel pink with cream floral motifs","bn":"পেস্টেল পিংকের উপর ক্রিম রঙের ফুলেল নকশা"}}'::jsonb, 'null'::jsonb, 4.5, 18
from public.categories c left join public.collections col on col.slug='everyday-elegance' where c.slug='unstitched-three-piece'
on conflict (slug) do update set name_en=excluded.name_en,description_en=excluded.description_en,category_id=excluded.category_id,collection_id=excluded.collection_id,base_price=excluded.base_price,compare_at_price=excluded.compare_at_price,fabric_en=excluded.fabric_en,product_code=excluded.product_code,status=excluded.status,is_new=excluded.is_new,is_featured=excluded.is_featured,is_best_seller=excluded.is_best_seller,care_instructions_en=excluded.care_instructions_en,tags=excluded.tags,unstitched_details=excluded.unstitched_details,ready_made_details=excluded.ready_made_details;

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1769031364744-9fecc63d93cd?w=900&h=1125&fit=crop&q=80&auto=format', 'Floral Cotton Unstitched Set', 0, true from public.products p where p.slug='floral-cotton-unstitched-set' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1769031364744-9fecc63d93cd?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=900&h=1125&fit=crop&q=80&auto=format', 'Floral Cotton Unstitched Set', 1, false from public.products p where p.slug='floral-cotton-unstitched-set' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-UN-102-UNDREADY-PASTEL-PINK', 'Unready', 'Pastel Pink', '#D8B4A0', 10, true from public.products where slug='floral-cotton-unstitched-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-UN-102-UNDREADY-BEIGE', 'Unready', 'Beige', '#C9BBA5', 10, true from public.products where slug='floral-cotton-unstitched-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.reviews(product_id,author_name,rating,comment_en,status,created_at) select p.id, 'Sadia R.', 5, 'Perfect for summer, very breathable fabric.', 'approved', '2026-04-11T00:00:00Z'::timestamptz from public.products p where p.slug='floral-cotton-unstitched-set' and not exists (select 1 from public.reviews existing where existing.product_id=p.id and existing.author_name='Sadia R.' and existing.created_at='2026-04-11T00:00:00Z'::timestamptz);

insert into public.products(slug,name_en,description_en,category_id,collection_id,base_price,compare_at_price,fabric_en,product_code,status,is_new,is_featured,is_best_seller,care_instructions_en,tags,unstitched_details,ready_made_details,average_rating,review_count) select 'wine-chikankari-unstitched-set', 'Wine Chikankari Unstitched Set', 'Rich wine-coloured georgette with traditional chikankari hand embroidery, perfect for festive occasions and gatherings.', c.id, col.id, 4200, 4900, 'Georgette', 'TR-UN-103', 'active', false, true, true, 'Dry clean only. Store folded in a cool dry place away from direct sunlight.', array['chikankari','festive','georgette'], '{"kameezFabric":{"en":"Georgette, 3.25 metres","bn":"জর্জেট, ৩.২৫ মিটার"},"salwarFabric":{"en":"Silk Blend, 2.5 metres","bn":"সিল্ক ব্লেন্ড, ২.৫ মিটার"},"dupattaFabric":{"en":"Net with Border, 2.5 metres","bn":"বর্ডারসহ নেট, ২.৫ মিটার"},"workDetails":{"en":"Hand chikankari embroidery with sequin highlights","bn":"সিকুইনের কাজসহ হাতের চিকনকারি এমব্রয়ডারি"},"fabricLength":{"en":"Total 8.25 metres (undready)","bn":"মোট ৮.২৫ মিটার (আনস্টিচড)"},"colourInfo":{"en":"Deep wine with gold thread accents","bn":"গোল্ডেন সুতার কাজসহ গাঢ় ওয়াইন রং"}}'::jsonb, 'null'::jsonb, 4.9, 41
from public.categories c left join public.collections col on col.slug='festive' where c.slug='unstitched-three-piece'
on conflict (slug) do update set name_en=excluded.name_en,description_en=excluded.description_en,category_id=excluded.category_id,collection_id=excluded.collection_id,base_price=excluded.base_price,compare_at_price=excluded.compare_at_price,fabric_en=excluded.fabric_en,product_code=excluded.product_code,status=excluded.status,is_new=excluded.is_new,is_featured=excluded.is_featured,is_best_seller=excluded.is_best_seller,care_instructions_en=excluded.care_instructions_en,tags=excluded.tags,unstitched_details=excluded.unstitched_details,ready_made_details=excluded.ready_made_details;

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1571513722275-4b41940f54b8?w=900&h=1125&fit=crop&q=80&auto=format', 'Wine Chikankari Unstitched Set', 0, true from public.products p where p.slug='wine-chikankari-unstitched-set' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1571513722275-4b41940f54b8?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=900&h=1125&fit=crop&q=80&auto=format', 'Wine Chikankari Unstitched Set', 1, false from public.products p where p.slug='wine-chikankari-unstitched-set' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1445205170230-053b83016050?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-UN-103-UNDREADY-WINE', 'Unready', 'Wine', '#6F263D', 8, true from public.products where slug='wine-chikankari-unstitched-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.reviews(product_id,author_name,rating,comment_en,status,created_at) select p.id, 'Tasnim H.', 5, 'Absolutely stunning for weddings, got so many compliments.', 'approved', '2026-03-15T00:00:00Z'::timestamptz from public.products p where p.slug='wine-chikankari-unstitched-set' and not exists (select 1 from public.reviews existing where existing.product_id=p.id and existing.author_name='Tasnim H.' and existing.created_at='2026-03-15T00:00:00Z'::timestamptz);

insert into public.products(slug,name_en,description_en,category_id,collection_id,base_price,compare_at_price,fabric_en,product_code,status,is_new,is_featured,is_best_seller,care_instructions_en,tags,unstitched_details,ready_made_details,average_rating,review_count) select 'black-embroidered-unstitched-set', 'Black Embroidered Unstitched Set', 'A timeless black cotton silk set with subtle self-tone embroidery, versatile enough for both work and evening wear.', c.id, col.id, 3100, null, 'Cotton Silk', 'TR-UN-104', 'active', false, false, true, 'Dry clean recommended for the first wash. Iron on low heat.', array['office','classic'], '{"kameezFabric":{"en":"Cotton Silk, 3.15 metres","bn":"কটন সিল্ক, ৩.১৫ মিটার"},"salwarFabric":{"en":"Cotton, 2.5 metres","bn":"কটন, ২.৫ মিটার"},"dupattaFabric":{"en":"Chiffon, 2.5 metres","bn":"শিফন, ২.৫ মিটার"},"workDetails":{"en":"Self-tone thread embroidery on neckline","bn":"গলায় সেলফ-টোন সুতার এমব্রয়ডারি"},"fabricLength":{"en":"Total 8.15 metres (undready)","bn":"মোট ৮.১৫ মিটার (আনস্টিচড)"},"colourInfo":{"en":"Solid black with tonal embroidery","bn":"একরঙা কালোর উপর সেলফ-টোন কাজ"}}'::jsonb, 'null'::jsonb, 4.6, 27
from public.categories c left join public.collections col on col.slug='office-edit' where c.slug='unstitched-three-piece'
on conflict (slug) do update set name_en=excluded.name_en,description_en=excluded.description_en,category_id=excluded.category_id,collection_id=excluded.collection_id,base_price=excluded.base_price,compare_at_price=excluded.compare_at_price,fabric_en=excluded.fabric_en,product_code=excluded.product_code,status=excluded.status,is_new=excluded.is_new,is_featured=excluded.is_featured,is_best_seller=excluded.is_best_seller,care_instructions_en=excluded.care_instructions_en,tags=excluded.tags,unstitched_details=excluded.unstitched_details,ready_made_details=excluded.ready_made_details;

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1642618277064-73c0bd608111?w=900&h=1125&fit=crop&q=80&auto=format', 'Black Embroidered Unstitched Set', 0, true from public.products p where p.slug='black-embroidered-unstitched-set' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1642618277064-73c0bd608111?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=900&h=1125&fit=crop&q=80&auto=format', 'Black Embroidered Unstitched Set', 1, false from public.products p where p.slug='black-embroidered-unstitched-set' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-UN-104-UNDREADY-BLACK', 'Unready', 'Black', '#171717', 16, true from public.products where slug='black-embroidered-unstitched-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.products(slug,name_en,description_en,category_id,collection_id,base_price,compare_at_price,fabric_en,product_code,status,is_new,is_featured,is_best_seller,care_instructions_en,tags,unstitched_details,ready_made_details,average_rating,review_count) select 'printed-cotton-unstitched-set', 'Printed Cotton Unstitched Set', 'An everyday beige cotton set with a soft geometric print, light enough for daily wear at home or work.', c.id, col.id, 1950, null, 'Cotton', 'TR-UN-105', 'active', false, false, false, 'Machine washable. Wash inside out to preserve print.', array['everyday','printed'], '{"kameezFabric":{"en":"Cotton, 3 metres","bn":"কটন, ৩ মিটার"},"salwarFabric":{"en":"Cotton, 2.5 metres","bn":"কটন, ২.৫ মিটার"},"dupattaFabric":{"en":"Cotton Voile, 2.5 metres","bn":"কটন ভয়েল, ২.৫ মিটার"},"workDetails":{"en":"Geometric print, no embellishment","bn":"জ্যামিতিক প্রিন্ট, কোনো বাড়তি কাজ নেই"},"fabricLength":{"en":"Total 8 metres (undready)","bn":"মোট ৮ মিটার (আনস্টিচড)"},"colourInfo":{"en":"Beige with brown geometric pattern","bn":"বাদামি জ্যামিতিক নকশাসহ বেইজ রং"}}'::jsonb, 'null'::jsonb, 4.3, 9
from public.categories c left join public.collections col on col.slug='everyday-elegance' where c.slug='unstitched-three-piece'
on conflict (slug) do update set name_en=excluded.name_en,description_en=excluded.description_en,category_id=excluded.category_id,collection_id=excluded.collection_id,base_price=excluded.base_price,compare_at_price=excluded.compare_at_price,fabric_en=excluded.fabric_en,product_code=excluded.product_code,status=excluded.status,is_new=excluded.is_new,is_featured=excluded.is_featured,is_best_seller=excluded.is_best_seller,care_instructions_en=excluded.care_instructions_en,tags=excluded.tags,unstitched_details=excluded.unstitched_details,ready_made_details=excluded.ready_made_details;

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=900&h=1125&fit=crop&q=80&auto=format', 'Printed Cotton Unstitched Set', 0, true from public.products p where p.slug='printed-cotton-unstitched-set' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=900&h=1125&fit=crop&q=80&auto=format', 'Printed Cotton Unstitched Set', 1, false from public.products p where p.slug='printed-cotton-unstitched-set' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1445205170230-053b83016050?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-UN-105-UNDREADY-BEIGE', 'Unready', 'Beige', '#C9BBA5', 25, true from public.products where slug='printed-cotton-unstitched-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.products(slug,name_en,description_en,category_id,collection_id,base_price,compare_at_price,fabric_en,product_code,status,is_new,is_featured,is_best_seller,care_instructions_en,tags,unstitched_details,ready_made_details,average_rating,review_count) select 'embroidered-lawn-kurta-set', 'Embroidered Lawn Kurta Set', 'A ready-to-wear ivory kurta set with hand embroidery detailing on the placket and cuffs, tailored for an easy, relaxed fit.', c.id, col.id, 2850, null, 'Pure Lawn Cotton', 'TR-RD-201', 'active', true, true, true, 'Dry clean recommended. Iron on medium heat, avoiding embroidered areas.', array['embroidered','ready-made'], 'null'::jsonb, '{"sizeMeasurements":[{"size":"S","chest":"36 in","waist":"32 in","length":"42 in"},{"size":"M","chest":"38 in","waist":"34 in","length":"42.5 in"},{"size":"L","chest":"40 in","waist":"36 in","length":"43 in"},{"size":"XL","chest":"42 in","waist":"38 in","length":"43.5 in"}],"modelHeight":{"en":"5 ft 6 in","bn":"৫ ফুট ৬ ইঞ্চি"},"modelWearingSize":"S","fitInformation":{"en":"Relaxed fit, true to size","bn":"রিল্যাক্সড ফিট, সাইজ অনুযায়ী সঠিক"}}'::jsonb, 4.8, 36
from public.categories c left join public.collections col on col.slug='festive' where c.slug='ready-three-piece'
on conflict (slug) do update set name_en=excluded.name_en,description_en=excluded.description_en,category_id=excluded.category_id,collection_id=excluded.collection_id,base_price=excluded.base_price,compare_at_price=excluded.compare_at_price,fabric_en=excluded.fabric_en,product_code=excluded.product_code,status=excluded.status,is_new=excluded.is_new,is_featured=excluded.is_featured,is_best_seller=excluded.is_best_seller,care_instructions_en=excluded.care_instructions_en,tags=excluded.tags,unstitched_details=excluded.unstitched_details,ready_made_details=excluded.ready_made_details;

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=900&h=1125&fit=crop&q=80&auto=format', 'Embroidered Lawn Kurta Set', 0, true from public.products p where p.slug='embroidered-lawn-kurta-set' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1483985988355-763728e1935b?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=900&h=1125&fit=crop&q=80&auto=format', 'Embroidered Lawn Kurta Set', 1, false from public.products p where p.slug='embroidered-lawn-kurta-set' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-201-S-IVORY', 'S', 'Ivory', '#EDE6D9', 5, true from public.products where slug='embroidered-lawn-kurta-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-201-M-IVORY', 'M', 'Ivory', '#EDE6D9', 5, true from public.products where slug='embroidered-lawn-kurta-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-201-L-IVORY', 'L', 'Ivory', '#EDE6D9', 5, true from public.products where slug='embroidered-lawn-kurta-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-201-XL-IVORY', 'XL', 'Ivory', '#EDE6D9', 5, true from public.products where slug='embroidered-lawn-kurta-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.reviews(product_id,author_name,rating,comment_en,status,created_at) select p.id, 'Rummana K.', 5, 'Fits perfectly, exactly as shown in pictures.', 'approved', '2026-06-18T00:00:00Z'::timestamptz from public.products p where p.slug='embroidered-lawn-kurta-set' and not exists (select 1 from public.reviews existing where existing.product_id=p.id and existing.author_name='Rummana K.' and existing.created_at='2026-06-18T00:00:00Z'::timestamptz);

insert into public.products(slug,name_en,description_en,category_id,collection_id,base_price,compare_at_price,fabric_en,product_code,status,is_new,is_featured,is_best_seller,care_instructions_en,tags,unstitched_details,ready_made_details,average_rating,review_count) select 'pastel-pink-co-ord-set', 'Pastel Pink Co-ord Set', 'A soft pastel pink georgette co-ord set with a flowy silhouette, ideal for daytime events and casual gatherings.', c.id, col.id, 2450, null, 'Georgette', 'TR-RD-202', 'active', true, true, false, 'Hand wash cold or dry clean. Hang dry in shade.', array['co-ord','pastel'], 'null'::jsonb, '{"sizeMeasurements":[{"size":"S","chest":"36 in","waist":"30 in","length":"41 in"},{"size":"M","chest":"38 in","waist":"32 in","length":"41.5 in"},{"size":"L","chest":"40 in","waist":"34 in","length":"42 in"}],"modelHeight":{"en":"5 ft 5 in","bn":"৫ ফুট ৫ ইঞ্চি"},"modelWearingSize":"S","fitInformation":{"en":"Flowy, relaxed silhouette","bn":"ফ্লোয়ি, রিল্যাক্সড সিলুয়েট"}}'::jsonb, 4.6, 14
from public.categories c left join public.collections col on col.slug='everyday-elegance' where c.slug='ready-three-piece'
on conflict (slug) do update set name_en=excluded.name_en,description_en=excluded.description_en,category_id=excluded.category_id,collection_id=excluded.collection_id,base_price=excluded.base_price,compare_at_price=excluded.compare_at_price,fabric_en=excluded.fabric_en,product_code=excluded.product_code,status=excluded.status,is_new=excluded.is_new,is_featured=excluded.is_featured,is_best_seller=excluded.is_best_seller,care_instructions_en=excluded.care_instructions_en,tags=excluded.tags,unstitched_details=excluded.unstitched_details,ready_made_details=excluded.ready_made_details;

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1769031364744-9fecc63d93cd?w=900&h=1125&fit=crop&q=80&auto=format', 'Pastel Pink Co-ord Set', 0, true from public.products p where p.slug='pastel-pink-co-ord-set' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1769031364744-9fecc63d93cd?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1784139021760-9f8ecb5c5586?w=900&h=1125&fit=crop&q=80&auto=format', 'Pastel Pink Co-ord Set', 1, false from public.products p where p.slug='pastel-pink-co-ord-set' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1784139021760-9f8ecb5c5586?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-202-S-PASTEL-PINK', 'S', 'Pastel Pink', '#D8B4A0', 2, true from public.products where slug='pastel-pink-co-ord-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-202-S-IVORY', 'S', 'Ivory', '#EDE6D9', 2, true from public.products where slug='pastel-pink-co-ord-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-202-M-PASTEL-PINK', 'M', 'Pastel Pink', '#D8B4A0', 2, true from public.products where slug='pastel-pink-co-ord-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-202-M-IVORY', 'M', 'Ivory', '#EDE6D9', 2, true from public.products where slug='pastel-pink-co-ord-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-202-L-PASTEL-PINK', 'L', 'Pastel Pink', '#D8B4A0', 2, true from public.products where slug='pastel-pink-co-ord-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-202-L-IVORY', 'L', 'Ivory', '#EDE6D9', 2, true from public.products where slug='pastel-pink-co-ord-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.products(slug,name_en,description_en,category_id,collection_id,base_price,compare_at_price,fabric_en,product_code,status,is_new,is_featured,is_best_seller,care_instructions_en,tags,unstitched_details,ready_made_details,average_rating,review_count) select 'black-embellished-kurta', 'Black Embellished Kurta', 'A structured black kurta with delicate hand embellishment on the collar, designed to transition effortlessly from day to night.', c.id, col.id, 2750, 3200, 'Cotton Silk', 'TR-RD-203', 'active', false, true, true, 'Dry clean only.', array['kurta','embellished'], 'null'::jsonb, '{"sizeMeasurements":[{"size":"S","chest":"36 in","waist":"32 in","length":"44 in"},{"size":"M","chest":"38 in","waist":"34 in","length":"44.5 in"},{"size":"L","chest":"40 in","waist":"36 in","length":"45 in"},{"size":"XL","chest":"42 in","waist":"38 in","length":"45.5 in"}],"modelHeight":{"en":"5 ft 6 in","bn":"৫ ফুট ৬ ইঞ্চি"},"modelWearingSize":"M","fitInformation":{"en":"Structured, tailored fit","bn":"স্ট্রাকচার্ড, টেইলর্ড ফিট"}}'::jsonb, 4.7, 29
from public.categories c left join public.collections col on col.slug='office-edit' where c.slug='ready-three-piece'
on conflict (slug) do update set name_en=excluded.name_en,description_en=excluded.description_en,category_id=excluded.category_id,collection_id=excluded.collection_id,base_price=excluded.base_price,compare_at_price=excluded.compare_at_price,fabric_en=excluded.fabric_en,product_code=excluded.product_code,status=excluded.status,is_new=excluded.is_new,is_featured=excluded.is_featured,is_best_seller=excluded.is_best_seller,care_instructions_en=excluded.care_instructions_en,tags=excluded.tags,unstitched_details=excluded.unstitched_details,ready_made_details=excluded.ready_made_details;

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1642618277064-73c0bd608111?w=900&h=1125&fit=crop&q=80&auto=format', 'Black Embellished Kurta', 0, true from public.products p where p.slug='black-embellished-kurta' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1642618277064-73c0bd608111?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1571513722275-4b41940f54b8?w=900&h=1125&fit=crop&q=80&auto=format', 'Black Embellished Kurta', 1, false from public.products p where p.slug='black-embellished-kurta' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1571513722275-4b41940f54b8?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-203-S-BLACK', 'S', 'Black', '#171717', 4, true from public.products where slug='black-embellished-kurta' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-203-M-BLACK', 'M', 'Black', '#171717', 4, true from public.products where slug='black-embellished-kurta' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-203-L-BLACK', 'L', 'Black', '#171717', 4, true from public.products where slug='black-embellished-kurta' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-203-XL-BLACK', 'XL', 'Black', '#171717', 4, true from public.products where slug='black-embellished-kurta' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.reviews(product_id,author_name,rating,comment_en,status,created_at) select p.id, 'Ishrat J.', 5, 'So versatile, wore it to work and to a dinner both.', 'approved', '2026-05-02T00:00:00Z'::timestamptz from public.products p where p.slug='black-embellished-kurta' and not exists (select 1 from public.reviews existing where existing.product_id=p.id and existing.author_name='Ishrat J.' and existing.created_at='2026-05-02T00:00:00Z'::timestamptz);

insert into public.products(slug,name_en,description_en,category_id,collection_id,base_price,compare_at_price,fabric_en,product_code,status,is_new,is_featured,is_best_seller,care_instructions_en,tags,unstitched_details,ready_made_details,average_rating,review_count) select 'wine-georgette-ready-set', 'Wine Georgette Ready Set', 'An elegant ready-to-wear wine georgette three piece with sequin embroidery, made for festive celebrations.', c.id, col.id, 4600, null, 'Georgette', 'TR-RD-204', 'active', false, false, true, 'Dry clean only. Store on a padded hanger.', array['festive','embellished'], 'null'::jsonb, '{"sizeMeasurements":[{"size":"S","chest":"36 in","waist":"32 in","length":"43 in"},{"size":"M","chest":"38 in","waist":"34 in","length":"43.5 in"},{"size":"L","chest":"40 in","waist":"36 in","length":"44 in"}],"modelHeight":{"en":"5 ft 6 in","bn":"৫ ফুট ৬ ইঞ্চি"},"modelWearingSize":"S","fitInformation":{"en":"Semi-fitted, flows from the waist","bn":"সেমি-ফিটেড, কোমর থেকে ফ্লোয়ি"}}'::jsonb, 4.9, 22
from public.categories c left join public.collections col on col.slug='festive' where c.slug='ready-three-piece'
on conflict (slug) do update set name_en=excluded.name_en,description_en=excluded.description_en,category_id=excluded.category_id,collection_id=excluded.collection_id,base_price=excluded.base_price,compare_at_price=excluded.compare_at_price,fabric_en=excluded.fabric_en,product_code=excluded.product_code,status=excluded.status,is_new=excluded.is_new,is_featured=excluded.is_featured,is_best_seller=excluded.is_best_seller,care_instructions_en=excluded.care_instructions_en,tags=excluded.tags,unstitched_details=excluded.unstitched_details,ready_made_details=excluded.ready_made_details;

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1571513722275-4b41940f54b8?w=900&h=1125&fit=crop&q=80&auto=format', 'Wine Georgette Ready Set', 0, true from public.products p where p.slug='wine-georgette-ready-set' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1571513722275-4b41940f54b8?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=900&h=1125&fit=crop&q=80&auto=format', 'Wine Georgette Ready Set', 1, false from public.products p where p.slug='wine-georgette-ready-set' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-204-S-WINE', 'S', 'Wine', '#6F263D', 2, true from public.products where slug='wine-georgette-ready-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-204-M-WINE', 'M', 'Wine', '#6F263D', 2, true from public.products where slug='wine-georgette-ready-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-204-L-WINE', 'L', 'Wine', '#6F263D', 2, true from public.products where slug='wine-georgette-ready-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.products(slug,name_en,description_en,category_id,collection_id,base_price,compare_at_price,fabric_en,product_code,status,is_new,is_featured,is_best_seller,care_instructions_en,tags,unstitched_details,ready_made_details,average_rating,review_count) select 'beige-linen-ready-set', 'Beige Linen Ready Set', 'A minimal beige linen three piece with clean lines, perfect for those who prefer understated everyday elegance.', c.id, col.id, 2650, null, 'Linen', 'TR-RD-205', 'active', false, false, false, 'Machine washable cold. Iron while slightly damp for best results.', array['linen','minimal'], 'null'::jsonb, '{"sizeMeasurements":[{"size":"S","chest":"36 in","waist":"32 in","length":"42 in"},{"size":"M","chest":"38 in","waist":"34 in","length":"42.5 in"},{"size":"L","chest":"40 in","waist":"36 in","length":"43 in"},{"size":"XL","chest":"42 in","waist":"38 in","length":"43.5 in"}],"modelHeight":{"en":"5 ft 5 in","bn":"৫ ফুট ৫ ইঞ্চি"},"modelWearingSize":"M","fitInformation":{"en":"Straight, relaxed fit","bn":"স্ট্রেইট, রিল্যাক্সড ফিট"}}'::jsonb, 4.4, 11
from public.categories c left join public.collections col on col.slug='everyday-elegance' where c.slug='ready-three-piece'
on conflict (slug) do update set name_en=excluded.name_en,description_en=excluded.description_en,category_id=excluded.category_id,collection_id=excluded.collection_id,base_price=excluded.base_price,compare_at_price=excluded.compare_at_price,fabric_en=excluded.fabric_en,product_code=excluded.product_code,status=excluded.status,is_new=excluded.is_new,is_featured=excluded.is_featured,is_best_seller=excluded.is_best_seller,care_instructions_en=excluded.care_instructions_en,tags=excluded.tags,unstitched_details=excluded.unstitched_details,ready_made_details=excluded.ready_made_details;

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=900&h=1125&fit=crop&q=80&auto=format', 'Beige Linen Ready Set', 0, true from public.products p where p.slug='beige-linen-ready-set' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=900&h=1125&fit=crop&q=80&auto=format', 'Beige Linen Ready Set', 1, false from public.products p where p.slug='beige-linen-ready-set' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-205-S-BEIGE', 'S', 'Beige', '#C9BBA5', 3, true from public.products where slug='beige-linen-ready-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-205-M-BEIGE', 'M', 'Beige', '#C9BBA5', 3, true from public.products where slug='beige-linen-ready-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-205-L-BEIGE', 'L', 'Beige', '#C9BBA5', 3, true from public.products where slug='beige-linen-ready-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-RD-205-XL-BEIGE', 'XL', 'Beige', '#C9BBA5', 3, true from public.products where slug='beige-linen-ready-set' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.products(slug,name_en,description_en,category_id,collection_id,base_price,compare_at_price,fabric_en,product_code,status,is_new,is_featured,is_best_seller,care_instructions_en,tags,unstitched_details,ready_made_details,average_rating,review_count) select 'minimal-shoulder-bag', 'Minimal Shoulder Bag', 'A structured minimal shoulder bag in soft beige leather, finished with gold-tone hardware and an adjustable strap.', c.id, col.id, 1650, null, 'Vegan Leather', 'TR-AC-301', 'active', true, true, true, 'Wipe with a soft, dry cloth. Avoid prolonged exposure to direct sunlight and moisture.', array['bag','everyday'], 'null'::jsonb, 'null'::jsonb, 4.6, 24
from public.categories c left join public.collections col on col.slug='accessories-edit' where c.slug='accessories'
on conflict (slug) do update set name_en=excluded.name_en,description_en=excluded.description_en,category_id=excluded.category_id,collection_id=excluded.collection_id,base_price=excluded.base_price,compare_at_price=excluded.compare_at_price,fabric_en=excluded.fabric_en,product_code=excluded.product_code,status=excluded.status,is_new=excluded.is_new,is_featured=excluded.is_featured,is_best_seller=excluded.is_best_seller,care_instructions_en=excluded.care_instructions_en,tags=excluded.tags,unstitched_details=excluded.unstitched_details,ready_made_details=excluded.ready_made_details;

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1711548244653-72219aa9ac27?w=900&h=1125&fit=crop&q=80&auto=format', 'Minimal Shoulder Bag', 0, true from public.products p where p.slug='minimal-shoulder-bag' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1711548244653-72219aa9ac27?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1691480150204-66dd1eb77391?w=900&h=1125&fit=crop&q=80&auto=format', 'Minimal Shoulder Bag', 1, false from public.products p where p.slug='minimal-shoulder-bag' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1691480150204-66dd1eb77391?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-AC-301-ONE-SIZE-BEIGE', 'One Size', 'Beige', '#C9BBA5', 15, true from public.products where slug='minimal-shoulder-bag' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-AC-301-ONE-SIZE-BLACK', 'One Size', 'Black', '#171717', 15, true from public.products where slug='minimal-shoulder-bag' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.reviews(product_id,author_name,rating,comment_en,status,created_at) select p.id, 'Meherun N.', 5, 'Great everyday size and the hardware looks premium.', 'approved', '2026-06-25T00:00:00Z'::timestamptz from public.products p where p.slug='minimal-shoulder-bag' and not exists (select 1 from public.reviews existing where existing.product_id=p.id and existing.author_name='Meherun N.' and existing.created_at='2026-06-25T00:00:00Z'::timestamptz);

insert into public.products(slug,name_en,description_en,category_id,collection_id,base_price,compare_at_price,fabric_en,product_code,status,is_new,is_featured,is_best_seller,care_instructions_en,tags,unstitched_details,ready_made_details,average_rating,review_count) select 'structured-tote-bag', 'Structured Tote Bag', 'A spacious black structured tote bag, ideal for daily essentials with a secure zip closure and interior pockets.', c.id, col.id, 1950, 2300, 'Vegan Leather', 'TR-AC-302', 'active', false, false, true, 'Wipe clean with a damp cloth. Store in dust bag when not in use.', array['bag','tote'], 'null'::jsonb, 'null'::jsonb, 4.5, 16
from public.categories c left join public.collections col on col.slug='accessories-edit' where c.slug='accessories'
on conflict (slug) do update set name_en=excluded.name_en,description_en=excluded.description_en,category_id=excluded.category_id,collection_id=excluded.collection_id,base_price=excluded.base_price,compare_at_price=excluded.compare_at_price,fabric_en=excluded.fabric_en,product_code=excluded.product_code,status=excluded.status,is_new=excluded.is_new,is_featured=excluded.is_featured,is_best_seller=excluded.is_best_seller,care_instructions_en=excluded.care_instructions_en,tags=excluded.tags,unstitched_details=excluded.unstitched_details,ready_made_details=excluded.ready_made_details;

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1705909237050-7a7625b47fac?w=900&h=1125&fit=crop&q=80&auto=format', 'Structured Tote Bag', 0, true from public.products p where p.slug='structured-tote-bag' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1705909237050-7a7625b47fac?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1605733513597-a8f8341084e6?w=900&h=1125&fit=crop&q=80&auto=format', 'Structured Tote Bag', 1, false from public.products p where p.slug='structured-tote-bag' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1605733513597-a8f8341084e6?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-AC-302-ONE-SIZE-BLACK', 'One Size', 'Black', '#171717', 21, true from public.products where slug='structured-tote-bag' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.products(slug,name_en,description_en,category_id,collection_id,base_price,compare_at_price,fabric_en,product_code,status,is_new,is_featured,is_best_seller,care_instructions_en,tags,unstitched_details,ready_made_details,average_rating,review_count) select 'pearl-drop-earrings', 'Pearl Drop Earrings', 'Elegant gold-plated drop earrings featuring freshwater pearl accents, a subtle finishing touch for any outfit.', c.id, col.id, 850, null, 'Gold-plated Brass, Freshwater Pearl', 'TR-AC-303', 'active', true, false, false, 'Keep away from water and perfume. Store in a jewellery pouch.', array['jewellery','earrings'], 'null'::jsonb, 'null'::jsonb, 4.8, 19
from public.categories c left join public.collections col on col.slug='accessories-edit' where c.slug='accessories'
on conflict (slug) do update set name_en=excluded.name_en,description_en=excluded.description_en,category_id=excluded.category_id,collection_id=excluded.collection_id,base_price=excluded.base_price,compare_at_price=excluded.compare_at_price,fabric_en=excluded.fabric_en,product_code=excluded.product_code,status=excluded.status,is_new=excluded.is_new,is_featured=excluded.is_featured,is_best_seller=excluded.is_best_seller,care_instructions_en=excluded.care_instructions_en,tags=excluded.tags,unstitched_details=excluded.unstitched_details,ready_made_details=excluded.ready_made_details;

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1561828995-aa79a2db86dd?w=900&h=1125&fit=crop&q=80&auto=format', 'Pearl Drop Earrings', 0, true from public.products p where p.slug='pearl-drop-earrings' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1561828995-aa79a2db86dd?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1657291334522-6c1dfb9e2b35?w=900&h=1125&fit=crop&q=80&auto=format', 'Pearl Drop Earrings', 1, false from public.products p where p.slug='pearl-drop-earrings' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1657291334522-6c1dfb9e2b35?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-AC-303-ONE-SIZE-GOLD', 'One Size', 'Gold', '#B8974E', 40, true from public.products where slug='pearl-drop-earrings' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

insert into public.products(slug,name_en,description_en,category_id,collection_id,base_price,compare_at_price,fabric_en,product_code,status,is_new,is_featured,is_best_seller,care_instructions_en,tags,unstitched_details,ready_made_details,average_rating,review_count) select 'layered-gold-necklace', 'Layered Gold Necklace', 'A delicate layered necklace in gold-tone finish, designed to be worn alone or stacked for a festive look.', c.id, col.id, 1250, null, 'Gold-plated Brass', 'TR-AC-304', 'active', false, true, false, 'Avoid contact with water, perfume, and lotion to preserve the finish.', array['jewellery','necklace','festive'], 'null'::jsonb, 'null'::jsonb, 4.6, 12
from public.categories c left join public.collections col on col.slug='festive' where c.slug='accessories'
on conflict (slug) do update set name_en=excluded.name_en,description_en=excluded.description_en,category_id=excluded.category_id,collection_id=excluded.collection_id,base_price=excluded.base_price,compare_at_price=excluded.compare_at_price,fabric_en=excluded.fabric_en,product_code=excluded.product_code,status=excluded.status,is_new=excluded.is_new,is_featured=excluded.is_featured,is_best_seller=excluded.is_best_seller,care_instructions_en=excluded.care_instructions_en,tags=excluded.tags,unstitched_details=excluded.unstitched_details,ready_made_details=excluded.ready_made_details;

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1657603738389-951c374b740c?w=900&h=1125&fit=crop&q=80&auto=format', 'Layered Gold Necklace', 0, true from public.products p where p.slug='layered-gold-necklace' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1657603738389-951c374b740c?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_images(product_id,image_url,alt_en,sort_order,is_primary) select p.id, 'https://images.unsplash.com/photo-1561828995-aa79a2db86dd?w=900&h=1125&fit=crop&q=80&auto=format', 'Layered Gold Necklace', 1, false from public.products p where p.slug='layered-gold-necklace' and not exists (select 1 from public.product_images existing where existing.product_id=p.id and existing.image_url='https://images.unsplash.com/photo-1561828995-aa79a2db86dd?w=900&h=1125&fit=crop&q=80&auto=format');

insert into public.product_variants(product_id,sku,size,colour_en,colour_hex,stock_quantity,is_active) select id, 'TR-AC-304-ONE-SIZE-GOLD', 'One Size', 'Gold', '#B8974E', 27, true from public.products where slug='layered-gold-necklace' on conflict (sku) do update set size=excluded.size,colour_en=excluded.colour_en,colour_hex=excluded.colour_hex,is_active=true;

commit;
